name: Publish Nuget Packget

on:
  release:
    type: [Published]
    
jobs:
  publish_to_nuget:
    runs-on: ubuntu-latest
    env:
      Solution_Name: BackgroundTaskQueue.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: dotnet restore ./${{ env.Solution_Name }} -c Release

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create the app package
      run: dotnet pack ./${{ env.Solution_Name }} -c Release

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload Nuget Package
      env:
        API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./src/UFG.BackgroundTaskQueue/bin/Release/BackgroundTaskQueue.${{  github.ref_name }}.nupkg --api-key ${{ env.API_KEY }} --source https://api.nuget.org/v3/index.json
